export const emptyInput = 'emptyInput';
export const invalid = 'invalid';
export const FETCH_ALL = 'FETCH_ALL';
export const RESULT = 'RESULT';
export const result = 'result';
export const OPEN = 'OPEN';
export const ADD = 'ADD';
export const REMOVE = 'REMOVE';
export const CLOSE = 'CLOSE';
export const LOGOUT = 'LOGOUT';
export const ERROR = 'ERROR';
export const END_LOADING = 'END_LOADING';
export const START_LOADING = 'START_LOADING';
export const FETCH_LABELS = 'FETCH_LABELS';
export const UPDATE_IMAGE = 'UPDATE_IMAGE';
export const UPDATE_FILE_IMAGE = 'UPDATE_FILE_IMAGE';
export const IMAGE_URL = 'https://images.unsplash.com/photo-1554692918-08fa0fdc9db3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwyMTYyOTB8MHwxfHNlYXJjaHw5fHxjb3JnaXxlbnwwfHx8fDE2MzIzMDA1OTg&ixlib=rb-1.2.1&q=80&w=1080'