food_labels=['apple pie', 'baby back ribs', 'baklava', 'beef carpaccio', 'beef tartare', 'beet salad', 'beignets', 'bibimbap', 'bread pudding', 'breakfast burrito', 'bruschetta', 'caesar salad', 'cannoli', 'caprese salad', 'carrot cake', 'ceviche', 'cheesecake', 'cheese plate', 'chicken curry', 'chicken quesadilla', 'chicken wings', 'chocolate cake', 'chocolate mousse', 'churros', 'clam chowder', 'club sandwich', 'crab cakes', 'creme brulee', 'croque madame', 'cup cakes', 'deviled eggs', 'donuts', 'dumplings', 'edamame', 'eggs benedict', 'escargots', 'falafel', 'filet mignon', 'fish and chips', 'foie gras', 'french fries', 'french onion soup', 'french toast', 'fried calamari', 'fried rice', 'frozen yogurt', 'garlic bread', 'gnocchi', 'greek salad', 'grilled cheese sandwich', 'grilled salmon', 'guacamole', 'gyoza', 'hamburger', 'hot and sour soup', 'hot dog', 'huevos rancheros', 'hummus', 'ice cream', 'lasagna', 'lobster bisque', 'lobster roll sandwich', 'macaroni and cheese', 'macarons', 'miso soup', 'mussels', 'nachos', 'omelette', 'onion rings', 'oysters', 'pad thai', 'paella', 'pancakes', 'panna cotta', 'peking duck', 'pho', 'pizza', 'pork chop', 'poutine', 'prime rib', 'pulled pork sandwich', 'ramen', 'ravioli', 'red velvet cake', 'risotto', 'samosa', 'sashimi', 'scallops', 'seaweed salad', 'shrimp and grits', 'spaghetti bolognese', 'spaghetti carbonara', 'spring rolls', 'steak', 'strawberry shortcake', 'sushi', 'tacos', 'takoyaki', 'tiramisu', 'tuna tartare', 'waffles']
# dog_breeds_labels=['affenpinscher','afghan_hound','african_hunting_dog','airedale','american_staffordshire_terrier','appenzeller','australian_terrier','basenji','basset','beagle','bedlington_terrier','bernese_mountain_dog','black-and-tan_coonhound','blenheim_spaniel','bloodhound','bluetick','border_collie','border_terrier','borzoi','boston_bull','bouvier_des_flandres','boxer','brabancon_griffon','briard','brittany_spaniel','bull_mastiff','cairn','cardigan','chesapeake_bay_retriever','chihuahua','chow','clumber','cocker_spaniel','collie','curly-coated_retriever','dandie_dinmont','dhole','dingo','doberman','english_foxhound','english_setter','english_springer','entlebucher','eskimo_dog','flat-coated_retriever','french_bulldog','german_shepherd','german_short-haired_pointer','giant_schnauzer','golden_retriever','gordon_setter','great_dane','great_pyrenees','greater_swiss_mountain_dog','groenendael','ibizan_hound','irish_setter','irish_terrier','irish_water_spaniel','irish_wolfhound','italian_greyhound','japanese_spaniel','keeshond','kelpie','kerry_blue_terrier','komondor','kuvasz','labrador_retriever','lakeland_terrier','leonberg','lhasa','malamute','malinois','maltese_dog','mexican_hairless','miniature_pinscher','miniature_poodle','miniature_schnauzer','newfoundland','norfolk_terrier','norwegian_elkhound','norwich_terrier','old_english_sheepdog','otterhound','papillon','pekinese','pembroke','pomeranian','pug','redbone','rhodesian_ridgeback','rottweiler','saint_bernard','saluki','samoyed','schipperke','scotch_terrier','scottish_deerhound','sealyham_terrier','shetland_sheepdog','shih-tzu','siberian_husky','silky_terrier','soft-coated_wheaten_terrier','staffordshire_bullterrier','standard_poodle','standard_schnauzer','sussex_spaniel','tibetan_mastiff','tibetan_terrier','toy_poodle','toy_terrier','vizsla','walker_hound','weimaraner','welsh_springer_spaniel','west_highland_white_terrier','whippet','wire-haired_fox_terrier','yorkshire_terrier'] 
dog_breeds_labels=['affenpinscher', 'afghan hound', 'african hunting dog', 'airedale', 'american staffordshire terrier', 'appenzeller', 'australian terrier', 'basenji', 'basset', 'beagle', 'bedlington terrier', 'bernese mountain dog', 'black-and-tan coonhound', 'blenheim spaniel', 'bloodhound', 'bluetick', 'border collie', 'border terrier', 'borzoi', 'boston bull', 'bouvier des flandres', 'boxer', 'brabancon griffon', 'briard', 'brittany spaniel', 'bull mastiff', 'cairn', 'cardigan', 'chesapeake bay retriever', 'chihuahua', 'chow', 'clumber', 'cocker spaniel', 'collie', 'curly-coated retriever', 'dandie dinmont', 'dhole', 'dingo', 'dobermann', 'english foxhound', 'english setter', 'english springer', 'entlebucher', 'eskimo dog', 'flat-coated retriever', 'french bulldog', 'german shepherd', 'german short-haired pointer', 'giant schnauzer', 'golden retriever', 'gordon setter', 'great dane', 'great pyrenees', 'greater swiss mountain dog', 'groenendael', 'ibizan hound', 'irish setter', 'irish terrier', 'irish water spaniel', 'irish wolfhound', 'italian greyhound', 'japanese spaniel', 'keeshond', 'kelpie', 'kerry blue terrier', 'komondor', 'kuvasz', 'labrador retriever', 'lakeland terrier', 'leonberg', 'lhasa', 'malamute', 'malinois', 'maltese dog', 'mexican hairless', 'miniature pinscher', 'miniature poodle', 'miniature schnauzer', 'newfoundland', 'norfolk terrier', 'norwegian elkhound', 'norwich terrier', 'old english sheepdog', 'otterhound', 'papillon', 'pekinese', 'Pembroke Welsh Corgi', 'pomeranian', 'pug', 'redbone', 'rhodesian ridgeback', 'rottweiler', 'saint bernard', 'saluki', 'samoyed', 'schipperke', 'scotch terrier', 'scottish deerhound', 'sealyham terrier', 'shetland sheepdog', 'shih-tzu', 'siberian husky', 'silky terrier', 'soft-coated wheaten terrier', 'staffordshire bullterrier', 'standard poodle', 'standard schnauzer', 'sussex spaniel', 'tibetan mastiff', 'tibetan terrier', 'toy poodle', 'toy terrier', 'vizsla', 'walker hound', 'weimaraner', 'welsh springer spaniel', 'west highland white terrier', 'whippet', 'wire-haired fox terrier', 'yorkshire terrier']

wildlife_labels=['bald eagle', 'black bear', 'bobcat', 'canada lynx', 'columbian black tailed deer', 
'cougar', 'coyote', 'deer', 'elk', 'gray fox', 'gray wolf', 'mountain beaver', 'nutria', 'raccoon', 
'raven', 'red fox', 'ringtail', 'sea lions', 'seals', 'virginia opossum']

birds_names_labels=['AFRICAN CROWNED CRANE','AFRICAN FIREFINCH','ALBATROSS','ALEXANDRINE PARAKEET',
'AMERICAN AVOCET','AMERICAN BITTERN','AMERICAN COOT','AMERICAN GOLDFINCH','AMERICAN KESTREL','AMERICAN PIPIT',
'AMERICAN REDSTART','ANHINGA','ANNAS HUMMINGBIRD','ANTBIRD','ARARIPE MANAKIN','ASIAN CRESTED IBIS','BALD EAGLE',
'BALD IBIS','BALI STARLING','BALTIMORE ORIOLE','BANANAQUIT','BANDED BROADBILL','BANDED PITA','BAR-TAILED GODWIT',
'BARN OWL','BARN SWALLOW','BARRED PUFFBIRD','BAY-BREASTED WARBLER','BEARDED BARBET','BEARDED BELLBIRD',
'BEARDED REEDLING','BELTED KINGFISHER','BIRD OF PARADISE','BLACK & YELLOW bROADBILL','BLACK FRANCOLIN',
'BLACK SKIMMER','BLACK SWAN','BLACK TAIL CRAKE','BLACK THROATED BUSHTIT','BLACK THROATED WARBLER','BLACK VULTURE',
'BLACK-CAPPED CHICKADEE','BLACK-NECKED GREBE','BLACK-THROATED SPARROW','BLACKBURNIAM WARBLER',
'BLONDE CRESTED WOODPECKER','BLUE GROUSE','BLUE HERON','BOBOLINK','BORNEAN BRISTLEHEAD','BORNEAN LEAFBIRD',
'BORNEAN PHEASANT','BROWN CREPPER','BROWN NOODY','BROWN THRASHER','BULWERS PHEASANT','CACTUS WREN',
'CALIFORNIA CONDOR','CALIFORNIA GULL','CALIFORNIA QUAIL','CANARY','CAPE MAY WARBLER','CAPPED HERON',
'CAPUCHINBIRD','CARMINE BEE-EATER','CASPIAN TERN','CASSOWARY','CEDAR WAXWING','CERULEAN WARBLER','CHARA DE COLLAR',
'CHIPPING SPARROW','CHUKAR PARTRIDGE','CINNAMON TEAL','CLARKS NUTCRACKER','COCK OF THE  ROCK','COCKATOO',
'COLLARED ARACARI','COMMON FIRECREST','COMMON GRACKLE','COMMON HOUSE MARTIN','COMMON LOON','COMMON POORWILL',
'COMMON STARLING','COUCHS KINGBIRD','CRESTED AUKLET','CRESTED CARACARA','CRESTED NUTHATCH','CRIMSON SUNBIRD',
'CROW','CROWNED PIGEON','CUBAN TODY','CUBAN TROGON','CURL CRESTED ARACURI','D-ARNAUDS BARBET','DARK EYED JUNCO',
'DOUBLE BARRED FINCH','DOUBLE BRESTED CORMARANT','DOWNY WOODPECKER','EASTERN BLUEBIRD','EASTERN MEADOWLARK',
'EASTERN ROSELLA','EASTERN TOWEE','ELEGANT TROGON','ELLIOTS  PHEASANT','EMPEROR PENGUIN','EMU','ENGGANO MYNA',
'EURASIAN GOLDEN ORIOLE','EURASIAN MAGPIE','EVENING GROSBEAK','FAIRY BLUEBIRD','FIRE TAILLED MYZORNIS',
'FLAME TANAGER','FLAMINGO','FRIGATE','GAMBELS QUAIL','GANG GANG COCKATOO','GILA WOODPECKER','GILDED FLICKER',
'GLOSSY IBIS','GO AWAY BIRD','GOLD WING WARBLER','GOLDEN CHEEKED WARBLER','GOLDEN CHLOROPHONIA','GOLDEN EAGLE',
'GOLDEN PHEASANT','GOLDEN PIPIT','GOULDIAN FINCH','GRAY CATBIRD','GRAY PARTRIDGE','GREAT POTOO',
'GREATOR SAGE GROUSE','GREEN BROADBILL','GREEN JAY','GREEN MAGPIE','GREY PLOVER','GUINEA TURACO','GUINEAFOWL',
'GYRFALCON','HARPY EAGLE','HAWAIIAN GOOSE','HELMET VANGA','HIMALAYAN MONAL','HOATZIN','HOODED MERGANSER','HOOPOES',
'HORNBILL','HORNED GUAN','HORNED LARK','HORNED SUNGEM','HOUSE FINCH','HOUSE SPARROW','IMPERIAL SHAQ','INCA TERN',
'INDIAN BUSTARD','INDIAN PITTA','INDIGO BUNTING','JABIRU','JAVA SPARROW','KAGU','KAKAPO','KILLDEAR','KING VULTURE',
'KIWI','KOOKABURRA','LARK BUNTING','LEARS MACAW','LILAC ROLLER','LONG-EARED OWL','MAGPIE GOOSE','MALABAR HORNBILL',
'MALACHITE KINGFISHER','MALAGASY WHITE EYE','MALEO','MALLARD DUCK','MANDRIN DUCK','MARABOU STORK','MASKED BOOBY',
'MASKED LAPWING','MIKADO  PHEASANT','MOURNING DOVE','MYNA','NICOBAR PIGEON','NOISY FRIARBIRD','NORTHERN BALD IBIS',
'NORTHERN CARDINAL','NORTHERN FLICKER','NORTHERN GANNET','NORTHERN GOSHAWK','NORTHERN JACANA',
'NORTHERN MOCKINGBIRD','NORTHERN PARULA','NORTHERN RED BISHOP','NORTHERN SHOVELER','OCELLATED TURKEY',
'OKINAWA RAIL','ORANGE BRESTED BUNTING','OSPREY','OSTRICH','OVENBIRD','OYSTER CATCHER','PAINTED BUNTIG',
'PALILA','PARADISE TANAGER','PARAKETT  AKULET','PARUS MAJOR','PEACOCK','PELICAN','PEREGRINE FALCON',
'PHILIPPINE EAGLE','PINK ROBIN','PUFFIN','PURPLE FINCH','PURPLE GALLINULE','PURPLE MARTIN','PURPLE SWAMPHEN',
'PYGMY KINGFISHER','QUETZAL','RAINBOW LORIKEET','RAZORBILL','RED BEARDED BEE EATER','RED BELLIED PITTA',
'RED BROWED FINCH','RED FACED CORMORANT','RED FACED WARBLER','RED HEADED DUCK','RED HEADED WOODPECKER',
'RED HONEY CREEPER','RED NAPED TROGON','RED TAILED HAWK','RED TAILED THRUSH','RED WINGED BLACKBIRD',
'RED WISKERED BULBUL','REGENT BOWERBIRD','RING-NECKED PHEASANT','ROADRUNNER','ROBIN','ROCK DOVE',
'ROSY FACED LOVEBIRD','ROUGH LEG BUZZARD','ROYAL FLYCATCHER','RUBY THROATED HUMMINGBIRD','RUDY KINGFISHER',
'RUFOUS KINGFISHER','RUFUOS MOTMOT','SAMATRAN THRUSH','SAND MARTIN','SANDHILL CRANE','SCARLET IBIS',
'SCARLET MACAW','SCARLET TANAGER','SHOEBILL','SHORT BILLED DOWITCHER','SMITHS LONGSPUR','SNOWY EGRET','SNOWY OWL',
'SORA','SPANGLED COTINGA','SPLENDID WREN','SPOON BILED SANDPIPER','SPOONBILL','SRI LANKA BLUE MAGPIE',
'STEAMER DUCK','STORK BILLED KINGFISHER','STRAWBERRY FINCH','STRIPPED MANAKIN','STRIPPED SWALLOW',
'SUPERB STARLING','SWINHOES PHEASANT','TAIWAN MAGPIE','TAKAHE','TASMANIAN HEN','TEAL DUCK','TIT MOUSE',
'TOUCHAN','TOWNSENDS WARBLER','TREE SWALLOW','TRUMPTER SWAN','TURKEY VULTURE','TURQUOISE MOTMOT',
'UMBRELLA BIRD','VARIED THRUSH','VENEZUELIAN TROUPIAL','VERMILION FLYCATHER','VICTORIA CROWNED PIGEON',
'VIOLET GREEN SWALLOW','VULTURINE GUINEAFOWL','WALL CREAPER','WATTLED CURASSOW','WHIMBREL','WHITE CHEEKED TURACO',
'WHITE NECKED RAVEN','WHITE TAILED TROPIC','WHITE THROATED BEE EATER','WILD TURKEY','WILSONS BIRD OF PARADISE',
'WOOD DUCK','YELLOW BELLIED FLOWERPECKER','YELLOW CACIQUE','YELLOW HEADED BLACKBIRD']

flowers_name_labels = ['Abutilon','Acacia','Aconite','AfricanDaisy','Agapanthus','Ageratum','Alchemilla','Allium',
'Alstroemeria','Alyssum','Amaranthus','Amaryllis','Anemone','AniseHyssop','ArmeriaMaritima','Aster','Azalea',
'Baby’sBreath','Bachelor’sButton','BalloonFlower','Ballota','BeeBalm','Begonia','Bellflower','Bergamot','Bergenia',
'Billbergia','Black-eyedSusan','BlanketFlower','BlazingStar','BleedingHeart','Bletilla','Blue-eyedGrass',
'Bluebonnets','BluestarFlower','Borage','Bottlebrush','Bouvardia','Brachyscome','Brassica','Broom','Buttercup',
'ButterflyBush','Calceolaria','Calendula','CaliforniaPoppy','CallaLily','Camellia','Candytuft','CannaLily',
'CapeLeadwort','CapePrimrose','CardinalFlower','Carnation','Catharanthus','Catmint','Celosia','CerastiumTomentosum',
'Chicory','Chionodoxa','Chrysanthemum','Clarkia','Clematis','Clover','Columbine','Coneflower','CoralBells',
'CoralVine','Coreopsis','Cornflower','Corydalis','Cosmos','Cotoneaster','Crocosmia','Crocus','CrownImperial',
'CuckooFlower','Cyclamen','Daffodil','Dahlia','Daisy','Dandelion','Daphne','Daylily','Decumaria','Delphinium',
'DesertRose','Deutzia','Dianella','Dianthusbarbatus','Diascia','Dietes','Dill','Disa','DutchIris','Echinops',
'Echium','Elder','EnglishBluebell','Epimedium','Eremurus','Erica','Erigeron','Euphorbia','Eustoma',
'EveningPrimrose','FallCrocus','Feverfew','Firethorn','FlamingKaty','FlannelFlower','FlaxFlower',
'FloweringDogwood','ForgetMeNot','Forsythia','FourO’clock','Foxglove','FrangipaniFlower','Freesia',
'FrenchMarigold','Fuchsia','Gaillardia','Gardenia','Gazania','Geranium','GerberaFlower','Gladiolas',
'Goldenrod','GrapeHyacinth','Guzmania','Hawthorn','Heather','Hebe','Helenium','Helichrysum','Heliotrope',
'Hellebore','Hibiscus','Holly','Hollyhock','Honeysuckle','Hosta','Hyacinth','Hydrangea','Hyssop','IcePlant',
'IcelandPoppy','Impatiens','IpomoeaLobata','Iris','Ixia','Ixora','Jacob’sLadder','Jasmine','JohnnyJumpUp',
'KaffirLily','Kalmia','KangarooPaw','Knautia','Kniphofia','Lady’sSlipper','Laelia','Lantana','Larkspur',
'Lavatera','Lavender','LemonVerbena','Lewesia','Lilac','Lily','LilyoftheValley','Linaria','Lotus','LoveintheMist',
'Lunaria','Lupin','Magnolia','MalteseCross','Mandevilla','MargueriteDaisy','Marigold','Matthiola','Mayflower',
'Meconopsis','Mimosa','Monk’sHood','MoonflowerVine','Moraea','MorningGlory','MossRose','Narcissus','Nasturtium',
'Nemesia','Nemophila','Neoregelia','Nerine','NewZealandTeaTree','Nierembergia','Nolana','Oleander','Olearia',
'Orchid','OrientalLily','OrientalPoppy','OrnamentalCherry','Ornithogalum','Osteospermum','Oxalis','OxeyeDaisy',
'OysterPlant','PaintedDaisy','Pansy','Parodia','PassionFlower','PeaceLily','Pelargonium','Penstemon','Peony',
'Periwinkle','PersianButtercup','Petunia','Phlox','Photinia','Physostegia','PincushionFlower','Pinks','Poinsettia',
'Polyanthus','Poppy','Potentilla','PowderPuff','QuakerLadies','QueenoftheMeadow','Queen’sCup','Quince','RainLily',
'RockRose','Rondeletia','RoseofSharon','Roses','Sage','SaintJohn’sWort','Scaevola','ScentedGeranium','Scilla',
'Sedum','ShastaDaisy','Silene','Snapdragon','Snowdrop','Snowflake','Soapwort','Speedwell','Starflower','Statice',
'Sunflower','SweetPea','TeaRose','TigerFlower','Tithonia','TobaccoPlant','Trachelium','Trillium','Triteleia',
'Tritoniacrocata','Trollius','TrumpetVine','Tuberose','Tulip','UrnPlant','Ursinia','UvaUrsi','Valerian','Verbena',
'Viburnum','Viola','VirginiaCreeper','Wallflower','Wandflower','Waterlilies','Watsonia','WaxPlant','Wedelia',
'Weigela','WhirlingButterflies','WinterJasmine','Winterberry','WishboneFlower','WoollyViolet',
'Xanthocerassorbifolium','Xerophyllum','Xylobium','Xylosma','Yarrow','Yellow-eyedGrass','YellowArchangel',
'YellowBell','Zenobia','Zinnia']