
food_labels=['apple pie', 'baby back ribs', 'baklava', 'beef carpaccio', 'beef tartare', 'beet salad', 'beignets', 'bibimbap',
'bread pudding', 'breakfast burrito', 'bruschetta', 'caesar salad', 'cannoli', 'caprese salad', 'carrot cake', 'ceviche',
'cheesecake', 'cheese plate', 'chicken curry', 'chicken quesadilla', 'chicken wings', 'chocolate cake', 'chocolate mousse',
'churros', 'clam chowder', 'club sandwich', 'crab cakes', 'creme brulee', 'croque madame', 'cup cakes', 'deviled eggs', 'donuts',
'dumplings', 'edamame', 'eggs benedict', 'escargots', 'falafel', 'filet mignon', 'fish and chips', 'foie gras', 'french fries',
'french onion soup', 'french toast', 'fried calamari', 'fried rice', 'frozen yogurt', 'garlic bread', 'gnocchi', 'greek salad',
'grilled cheese sandwich', 'grilled salmon', 'guacamole', 'gyoza', 'hamburger', 'hot and sour soup', 'hot dog',
'huevos rancheros', 'hummus', 'ice cream', 'lasagna', 'lobster bisque', 'lobster roll sandwich', 'macaroni and cheese',
'macarons', 'miso soup', 'mussels', 'nachos', 'omelette', 'onion rings', 'oysters', 'pad thai', 'paella', 'pancakes',
'panna cotta', 'peking duck', 'pho', 'pizza', 'pork chop', 'poutine', 'prime rib', 'pulled pork sandwich', 'ramen',
'ravioli', 'red velvet cake', 'risotto', 'samosa', 'sashimi', 'scallops', 'seaweed salad', 'shrimp and grits',
'spaghetti bolognese', 'spaghetti carbonara', 'spring rolls', 'steak', 'strawberry shortcake', 'sushi', 'tacos',
'takoyaki', 'tiramisu', 'tuna tartare', 'waffles']

dog_breeds_labels=['affenpinscher', 'afghan hound', 'african hunting dog', 'airedale', 'american staffordshire terrier', 'appenzeller',
'australian terrier', 'basenji', 'basset', 'beagle', 'bedlington terrier', 'bernese mountain dog', 'black-and-tan coonhound', 
'blenheim spaniel', 'bloodhound', 'bluetick', 'border collie', 'border terrier', 'borzoi', 'boston bull', 'bouvier des flandres',
'boxer', 'brabancon griffon', 'briard', 'brittany spaniel', 'bull mastiff', 'cairn', 'cardigan', 'chesapeake bay retriever',
'chihuahua', 'chow', 'clumber', 'cocker spaniel', 'collie', 'curly-coated retriever', 'dandie dinmont', 'dhole', 'dingo', 
'dobermann', 'english foxhound', 'english setter', 'english springer', 'entlebucher', 'eskimo dog', 'flat-coated retriever', 
'french bulldog', 'german shepherd', 'german short-haired pointer', 'giant schnauzer', 'golden retriever', 'gordon setter',
'great dane', 'great pyrenees', 'greater swiss mountain dog', 'groenendael', 'ibizan hound', 'irish setter', 'irish terrier',
'irish water spaniel', 'irish wolfhound', 'italian greyhound', 'japanese spaniel', 'keeshond', 'kelpie', 'kerry blue terrier',
'komondor', 'kuvasz', 'labrador retriever', 'lakeland terrier', 'leonberg', 'lhasa', 'malamute', 'malinois', 'maltese dog',
'mexican hairless', 'miniature pinscher', 'miniature poodle', 'miniature schnauzer', 'newfoundland', 'norfolk terrier',
'norwegian elkhound', 'norwich terrier', 'old english sheepdog', 'otterhound', 'papillon', 'pekinese', 'Pembroke Welsh Corgi',
'pomeranian', 'pug', 'redbone', 'rhodesian ridgeback', 'rottweiler', 'saint bernard', 'saluki', 'samoyed', 
'schipperke', 'scotch terrier', 'scottish deerhound', 'sealyham terrier', 'shetland sheepdog', 'shih-tzu',
'siberian husky', 'silky terrier', 'soft-coated wheaten terrier', 'staffordshire bullterrier', 'standard poodle',
'standard schnauzer', 'sussex spaniel', 'tibetan mastiff', 'tibetan terrier', 'toy poodle', 'toy terrier', 
'vizsla', 'walker hound', 'weimaraner', 'welsh springer spaniel', 'west highland white terrier', 'whippet',
'wire-haired fox terrier', 'yorkshire terrier']

wildlife_labels=['bald eagle', 'black bear', 'bobcat', 'canada lynx', 'columbian black tailed deer', 
'cougar', 'coyote', 'deer', 'elk', 'gray fox', 'gray wolf', 'mountain beaver', 'nutria', 'raccoon', 
'raven', 'red fox', 'ringtail', 'sea lions', 'seals', 'virginia opossum']

birds_names_labels=['ABBOTTS BABBLER', 'ABBOTTS BOOBY', 'ABYSSINIAN GROUND HORNBILL', 'AFRICAN CROWNED CRANE', 'AFRICAN EMERALD CUCKOO',
'AFRICAN FIREFINCH', 'AFRICAN OYSTER CATCHER', 'ALBATROSS', 'ALBERTS TOWHEE', 'ALEXANDRINE PARAKEET', 'ALPINE CHOUGH',
'ALTAMIRA YELLOWTHROAT', 'AMERICAN AVOCET', 'AMERICAN BITTERN', 'AMERICAN COOT', 'AMERICAN GOLDFINCH', 'AMERICAN KESTREL',
'AMERICAN PIPIT', 'AMERICAN REDSTART', 'AMETHYST WOODSTAR', 'ANDEAN GOOSE', 'ANDEAN LAPWING', 'ANDEAN SISKIN', 'ANHINGA',
'ANIANIAU', 'ANNAS HUMMINGBIRD', 'ANTBIRD', 'ANTILLEAN EUPHONIA', 'APAPANE', 'APOSTLEBIRD', 'ARARIPE MANAKIN',
'ASHY THRUSHBIRD', 'ASIAN CRESTED IBIS', 'AVADAVAT', 'AZURE JAY', 'AZURE TANAGER', 'AZURE TIT', 'BAIKAL TEAL',
'BALD EAGLE', 'BALD IBIS', 'BALI STARLING', 'BALTIMORE ORIOLE', 'BANANAQUIT', 'BAND TAILED GUAN', 'BANDED BROADBILL',
'BANDED PITA', 'BANDED STILT', 'BAR-TAILED GODWIT', 'BARN OWL', 'BARN SWALLOW', 'BARRED PUFFBIRD', 'BARROWS GOLDENEYE', 
'BAY-BREASTED WARBLER', 'BEARDED BARBET', 'BEARDED BELLBIRD', 'BEARDED REEDLING', 'BELTED KINGFISHER', 'BIRD OF PARADISE', 
'BLACK & YELLOW  BROADBILL', 'BLACK BAZA', 'BLACK COCKATO', 'BLACK FRANCOLIN', 'BLACK SKIMMER', 'BLACK SWAN', 'BLACK TAIL CRAKE', 
'BLACK THROATED BUSHTIT', 'BLACK THROATED WARBLER', 'BLACK VULTURE', 'BLACK-CAPPED CHICKADEE', 'BLACK-NECKED GREBE', 
'BLACK-THROATED SPARROW', 'BLACKBURNIAM WARBLER', 'BLONDE CRESTED WOODPECKER', 'BLUE COAU', 'BLUE GROUSE', 'BLUE HERON', 
'BLUE THROATED TOUCANET', 'BOBOLINK', 'BORNEAN BRISTLEHEAD', 'BORNEAN LEAFBIRD', 'BORNEAN PHEASANT', 'BRANDT CORMARANT', 
'BROWN CREPPER', 'BROWN NOODY', 'BROWN THRASHER', 'BULWERS PHEASANT', 'BUSH TURKEY', 'CACTUS WREN', 'CALIFORNIA CONDOR', 
'CALIFORNIA GULL', 'CALIFORNIA QUAIL', 'CANARY', 'CAPE GLOSSY STARLING', 'CAPE LONGCLAW', 'CAPE MAY WARBLER', 'CAPE ROCK THRUSH', 
'CAPPED HERON', 'CAPUCHINBIRD', 'CARMINE BEE-EATER', 'CASPIAN TERN', 'CASSOWARY', 'CEDAR WAXWING', 'CERULEAN WARBLER', 
'CHARA DE COLLAR', 'CHATTERING LORY', 'CHESTNET BELLIED EUPHONIA', 'CHINESE BAMBOO PARTRIDGE', 'CHINESE POND HERON', 
'CHIPPING SPARROW', 'CHUCAO TAPACULO', 'CHUKAR PARTRIDGE', 'CINNAMON ATTILA', 'CINNAMON FLYCATCHER', 'CINNAMON TEAL', 
'CLARKS NUTCRACKER', 'COCK OF THE  ROCK', 'COCKATOO', 'COLLARED ARACARI', 'COMMON FIRECREST', 'COMMON GRACKLE', 'COMMON HOUSE MARTIN', 
'COMMON IORA', 'COMMON LOON', 'COMMON POORWILL', 'COMMON STARLING', 'COPPERY TAILED COUCAL', 'CRAB PLOVER', 'CRANE HAWK', 
'CREAM COLORED WOODPECKER', 'CRESTED AUKLET', 'CRESTED CARACARA', 'CRESTED COUA', 'CRESTED FIREBACK', 'CRESTED KINGFISHER', 
'CRESTED NUTHATCH', 'CRESTED OROPENDOLA', 'CRESTED SHRIKETIT', 'CRIMSON CHAT', 'CRIMSON SUNBIRD', 'CROW', 'CROWNED PIGEON', 
'CUBAN TODY', 'CUBAN TROGON', 'CURL CRESTED ARACURI', 'D-ARNAUDS BARBET', 'DARK EYED JUNCO', 'DEMOISELLE CRANE', 
'DOUBLE BARRED FINCH', 'DOUBLE BRESTED CORMARANT', 'DOUBLE EYED FIG PARROT', 'DOWNY WOODPECKER', 'DUSKY LORY', 'EARED PITA', 
'EASTERN BLUEBIRD', 'EASTERN GOLDEN WEAVER', 'EASTERN MEADOWLARK', 'EASTERN ROSELLA', 'EASTERN TOWEE', 'ELEGANT TROGON', 
'ELLIOTS  PHEASANT', 'EMERALD TANAGER', 'EMPEROR PENGUIN', 'EMU', 'ENGGANO MYNA', 'EURASIAN GOLDEN ORIOLE', 'EURASIAN MAGPIE', 
'EUROPEAN GOLDFINCH', 'EUROPEAN TURTLE DOVE', 'EVENING GROSBEAK', 'FAIRY BLUEBIRD', 'FAIRY TERN', 'FIORDLAND PENGUIN', 
'FIRE TAILLED MYZORNIS', 'FLAME BOWERBIRD', 'FLAME TANAGER', 'FLAMINGO', 'FRIGATE', 'GAMBELS QUAIL', 'GANG GANG COCKATOO', 
'GILA WOODPECKER', 'GILDED FLICKER', 'GLOSSY IBIS', 'GO AWAY BIRD', 'GOLD WING WARBLER', 'GOLDEN CHEEKED WARBLER', 
'GOLDEN CHLOROPHONIA', 'GOLDEN EAGLE', 'GOLDEN PHEASANT', 'GOLDEN PIPIT', 'GOULDIAN FINCH', 'GRAY CATBIRD', 'GRAY KINGBIRD', 
'GRAY PARTRIDGE', 'GREAT GRAY OWL', 'GREAT JACAMAR', 'GREAT KISKADEE', 'GREAT POTOO', 'GREATOR SAGE GROUSE', 'GREEN BROADBILL', 
'GREEN JAY', 'GREEN MAGPIE', 'GREY PLOVER', 'GROVED BILLED ANI', 'GUINEA TURACO', 'GUINEAFOWL', 'GURNEYS PITTA', 'GYRFALCON', 
'HAMMERKOP', 'HARLEQUIN DUCK', 'HARLEQUIN QUAIL', 'HARPY EAGLE', 'HAWAIIAN GOOSE', 'HAWFINCH', 'HELMET VANGA', 'HEPATIC TANAGER', 
'HIMALAYAN BLUETAIL', 'HIMALAYAN MONAL', 'HOATZIN', 'HOODED MERGANSER', 'HOOPOES', 'HORNBILL', 'HORNED GUAN', 'HORNED LARK', 
'HORNED SUNGEM', 'HOUSE FINCH', 'HOUSE SPARROW', 'HYACINTH MACAW', 'IBERIAN MAGPIE', 'IBISBILL', 'IMPERIAL SHAQ', 'INCA TERN', 
'INDIAN BUSTARD', 'INDIAN PITTA', 'INDIAN ROLLER', 'INDIGO BUNTING', 'INLAND DOTTEREL', 'IVORY GULL', 'IWI', 'JABIRU', 'JACK SNIPE', 
'JANDAYA PARAKEET', 'JAPANESE ROBIN', 'JAVA SPARROW', 'KAGU', 'KAKAPO', 'KILLDEAR', 'KING VULTURE', 'KIWI', 'KOOKABURRA', 
'LARK BUNTING', 'LAZULI BUNTING', 'LESSER ADJUTANT', 'LILAC ROLLER', 'LITTLE AUK', 'LONG-EARED OWL', 'MAGPIE GOOSE', 
'MALABAR HORNBILL', 'MALACHITE KINGFISHER', 'MALAGASY WHITE EYE', 'MALEO', 'MALLARD DUCK', 'MANDRIN DUCK', 'MANGROVE CUCKOO', 
'MARABOU STORK', 'MASKED BOOBY', 'MASKED LAPWING', 'MIKADO  PHEASANT', 'MOURNING DOVE', 'MYNA', 'NICOBAR PIGEON', 'NOISY FRIARBIRD', 
'NORTHERN CARDINAL', 'NORTHERN FLICKER', 'NORTHERN FULMAR', 'NORTHERN GANNET', 'NORTHERN GOSHAWK', 'NORTHERN JACANA', 
'NORTHERN MOCKINGBIRD', 'NORTHERN PARULA', 'NORTHERN RED BISHOP', 'NORTHERN SHOVELER', 'OCELLATED TURKEY', 'OKINAWA RAIL', 
'ORANGE BRESTED BUNTING', 'ORIENTAL BAY OWL', 'OSPREY', 'OSTRICH', 'OVENBIRD', 'OYSTER CATCHER', 'PAINTED BUNTING', 'PALILA', 
'PARADISE TANAGER', 'PARAKETT  AKULET', 'PARUS MAJOR', 'PATAGONIAN SIERRA FINCH', 'PEACOCK', 'PELICAN', 'PEREGRINE FALCON', 
'PHILIPPINE EAGLE', 'PINK ROBIN', 'POMARINE JAEGER', 'PUFFIN', 'PURPLE FINCH', 'PURPLE GALLINULE', 'PURPLE MARTIN', 
'PURPLE SWAMPHEN', 'PYGMY KINGFISHER', 'QUETZAL', 'RAINBOW LORIKEET', 'RAZORBILL', 'RED BEARDED BEE EATER', 'RED BELLIED PITTA', 
'RED BROWED FINCH', 'RED FACED CORMORANT', 'RED FACED WARBLER', 'RED FODY', 'RED HEADED DUCK', 'RED HEADED WOODPECKER', 
'RED HONEY CREEPER', 'RED NAPED TROGON', 'RED TAILED HAWK', 'RED TAILED THRUSH', 'RED WINGED BLACKBIRD', 'RED WISKERED BULBUL', 
'REGENT BOWERBIRD', 'RING-NECKED PHEASANT', 'ROADRUNNER', 'ROBIN', 'ROCK DOVE', 'ROSY FACED LOVEBIRD', 'ROUGH LEG BUZZARD', 
'ROYAL FLYCATCHER', 'RUBY THROATED HUMMINGBIRD', 'RUDY KINGFISHER', 'RUFOUS KINGFISHER', 'RUFUOS MOTMOT', 'SAMATRAN THRUSH', 
'SAND MARTIN', 'SANDHILL CRANE', 'SATYR TRAGOPAN', 'SCARLET CROWNED FRUIT DOVE', 'SCARLET IBIS', 'SCARLET MACAW', 'SCARLET TANAGER', 
'SHOEBILL', 'SHORT BILLED DOWITCHER', 'SMITHS LONGSPUR', 'SNOWY EGRET', 'SNOWY OWL', 'SORA', 'SPANGLED COTINGA', 'SPLENDID WREN', 
'SPOON BILED SANDPIPER', 'SPOONBILL', 'SPOTTED CATBIRD', 'SRI LANKA BLUE MAGPIE', 'STEAMER DUCK', 'STORK BILLED KINGFISHER', 
'STRAWBERRY FINCH', 'STRIPED OWL', 'STRIPPED MANAKIN', 'STRIPPED SWALLOW', 'SUPERB STARLING', 'SWINHOES PHEASANT', 'TAILORBIRD', 
'TAIWAN MAGPIE', 'TAKAHE', 'TASMANIAN HEN', 'TEAL DUCK', 'TIT MOUSE', 'TOUCHAN', 'TOWNSENDS WARBLER', 'TREE SWALLOW', 
'TROPICAL KINGBIRD', 'TRUMPTER SWAN', 'TURKEY VULTURE', 'TURQUOISE MOTMOT', 'UMBRELLA BIRD', 'VARIED THRUSH', 'VENEZUELIAN TROUPIAL', 
'VERMILION FLYCATHER', 'VICTORIA CROWNED PIGEON', 'VIOLET GREEN SWALLOW', 'VIOLET TURACO', 'VULTURINE GUINEAFOWL', 'WALL CREAPER', 
'WATTLED CURASSOW', 'WATTLED LAPWING', 'WHIMBREL', 'WHITE BROWED CRAKE', 'WHITE CHEEKED TURACO', 'WHITE NECKED RAVEN', 
'WHITE TAILED TROPIC', 'WHITE THROATED BEE EATER', 'WILD TURKEY', 'WILSONS BIRD OF PARADISE', 'WOOD DUCK', 'YELLOW BELLIED FLOWERPECKER',
'YELLOW CACIQUE', 'YELLOW HEADED BLACKBIRD']

flowers_name_labels = ['Abutilon','Acacia','Aconite','African Daisy','Agapanthus','Ageratum','Alchemilla','Allium',
'Alstroemeria','Alyssum','Amaranthus','Amaryllis','Anemone','Anise Hyssop','Armeria Maritima','Aster','Azalea',
'Baby’s Breath','Bachelor’s Button','Balloon Flower','Ballota','Bee Balm','Begonia','Bell flower','Bergamot','Bergenia',
'Billbergia','Black-eyedSusan','Blanket Flower','Blazing Star','Bleeding Heart','Bletilla','Blue-eyedGrass',
'Bluebonnets','Bluestar Flower','Borage','Bottlebrush','Bouvardia','Brachyscome','Brassica','Broom','Buttercup',
'Butterfly Bush','Calceolaria','Calendula','California Poppy','Calla Lily','Camellia','Candytuft','Canna Lily',
'Cape Leadwort','Cape Primrose','Cardinal Flower','Carnation','Catharanthus','Catmint','Celosia','Cerastium Tomentosum',
'Chicory','Chionodoxa','Chrysanthemum','Clarkia','Clematis','Clover','Columbine','Cone flower','Coral Bells',
'Coral Vine','Coreopsis','Corn flower','Corydalis','Cosmos','Cotoneaster','Crocosmia','Crocus','Crown Imperial',
'Cuckoo Flower','Cyclamen','Daffodil','Dahlia','Daisy','Dandelion','Daphne','Daylily','Decumaria','Delphinium',
'DesertRose','Deutzia','Dianella','Dianthusbarbatus','Diascia','Dietes','Dill','Disa','Dutch Iris','Echinops',
'Echium','Elder','English Bluebell','Epimedium','Eremurus','Erica','Erigeron','Euphorbia','Eustoma',
'Evening Primrose','Fall Crocus','Feverfew','Firethorn','Flaming Katy','Flannel Flower','Flax Flower',
'Flowering Dogwood','ForgetMeNot','Forsythia','Four O’clock','Foxglove','Frangipani Flower','Freesia',
'French Marigold','Fuchsia','Gaillardia','Gardenia','Gazania','Geranium','Gerbera Flower','Gladiolas',
'Goldenrod','Grape Hyacinth','Guzmania','Hawthorn','Heather','Hebe','Helenium','Helichrysum','Heliotrope',
'Hellebore','Hibiscus','Holly','Hollyhock','Honeysuckle','Hosta','Hyacinth','Hydrangea','Hyssop','Ice Plant',
'Iceland Poppy','Impatiens','Ipomoea Lobata','Iris','Ixia','Ixora','Jacob’s Ladder','Jasmine','Johnny Jump Up',
'Kaffir Lily','Kalmia','Kangaroo Paw','Knautia','Kniphofia','Lady’s Slipper','Laelia','Lantana','Larkspur',
'Lavatera','Lavender','Lemon Verbena','Lewesia','Lilac','Lily','Lilyofthe Valley','Linaria','Lotus','Loveinthe Mist',
'Lunaria','Lupin','Magnolia','Maltese Cross','Mandevilla','Marguerite Daisy','Marigold','Matthiola','May flower',
'Meconopsis','Mimosa','Monk’s Hood','Moon flower Vine','Moraea','Morning Glory','Moss Rose','Narcissus','Nasturtium',
'Nemesia','Nemophila','Neoregelia','Nerine','New Zealand Tea Tree','Nierembergia','Nolana','Oleander','Olearia',
'Orchid','Oriental Lily','Oriental Poppy','Ornamental Cherry','Ornithogalum','Osteospermum','Oxalis','Oxeye Daisy',
'Oyster Plant','Painted Daisy','Pansy','Parodia','Passion Flower','Peace Lily','Pelargonium','Penstemon','Peony',
'Periwinkle','Persian Buttercup','Petunia','Phlox','Photinia','Physostegia','Pincushion Flower','Pinks','Poinsettia',
'Polyanthus','Poppy','Potentilla','Powder Puff','Quaker Ladies','Queen of the Meadow','Queen’s Cup','Quince','Rain Lily',
'Rock Rose','Rondeletia','Rose of Sharon','Roses','Sage','Saint John’s Wort','Scaevola','Scented Geranium','Scilla',
'Sedum','Shasta Daisy','Silene','Snapdragon','Snowdrop','Snowflake','Soapwort','Speedwell','Star flower','Statice',
'Sun flower','Sweet Pea','Tea Rose','Tiger Flower','Tithonia','Tobacco Plant','Trachelium','Trillium','Triteleia',
'Tritoniacrocata','Trollius','Trumpet Vine','Tuberose','Tulip','Urn Plant','Ursinia','Uva Ursi','Valerian','Verbena',
'Viburnum','Viola','Virginia Creeper','Wall flower','Wand flower','Water lilies','Watsonia','Wax Plant','Wedelia',
'Weigela','Whirling Butterflies','Winter Jasmine','Winter berry','Wishbone Flower','Woolly Violet',
'Xanthocerassorbifolium','Xerophyllum','Xylobium','Xylosma','Yarrow','Yellow-eyed Grass','Yellow Archangel',
'Yellow Bell','Zenobia','Zinnia']

animal_labels=['antelope','badger','bat','bear','bee','beetle','bison','boar','butterfly','cat',
'caterpillar','chimpanzee','cockroach','cow','coyote','crab','crow','deer','dog','dolphin','donkey',
'dragonfly','duck','eagle','elephant','flamingo','fly','fox','goat','goldfish','goose','gorilla',
'grasshopper','hamster','hare','hedgehog','hippopotamus','hornbill','horse','hummingbird','hyena',
'jellyfish','kangaroo','koala','ladybugs','leopard','lion','lizard','lobster','mosquito','moth',
'mouse','octopus','okapi','orangutan','otter','owl','ox','oyster','panda','parrot','pelecaniformes',
'penguin','pig','pigeon','porcupine','possum','raccoon','rat','reindeer','rhinoceros','sandpiper',
'seahorse','seal','shark','sheep','snake','sparrow','squid','squirrel','starfish','swan','tiger',
'turkey','turtle','whale','wolf','wombat','woodpecker','zebra']

places365=['airplane_cabin','airport_terminal','alcove','alley','amphitheater','amusement_arcade','amusement_park','apartment_building-outdoor',
 'aquarium','aqueduct','arcade','arch','archaelogical_excavation','archive','arena-hockey','arena-performance','arena-rodeo',
 'army_base','art_gallery','art_school','art_studio','artists_loft','assembly_line','athletic_field-outdoor','atrium-public',
 'attic','auditorium','auto_factory','auto_showroom','badlands','bakery-shop','balcony-exterior','balcony-interior','ball_pit',
 'ballroom','bamboo_forest','bank_vault','banquet_hall','bar','barn','barndoor','baseball_field','basement','basketball_court-indoor',
 'bathroom','bazaar-indoor','bazaar-outdoor','beach','beach_house','beauty_salon','bedchamber','bedroom','beer_garden','beer_hall',
 'berth','biology_laboratory','boardwalk','boat_deck','boathouse','bookstore','booth-indoor','botanical_garden','bow_window-indoor',
 'bowling_alley','boxing_ring','bridge','building_facade','bullring','burial_chamber','bus_interior','bus_station-indoor',
 'butchers_shop','butte','cabin-outdoor','cafeteria','campsite','campus','canal-natural','canal-urban','candy_store',
 'canyon','car_interior','carrousel','castle','catacomb','cemetery','chalet','chemistry_lab','childs_room','church-indoor',
 'church-outdoor','classroom','clean_room','cliff','closet','clothing_store','coast','cockpit','coffee_shop','computer_room',
 'conference_center','conference_room','construction_site','corn_field','corral','corridor','cottage','courthouse','courtyard',
 'creek','crevasse','crosswalk','dam','delicatessen','department_store','desert-sand','desert-vegetation','desert_road',
 'diner-outdoor','dining_hall','dining_room','discotheque','doorway-outdoor','dorm_room','downtown','dressing_room','driveway',
 'drugstore','elevator-door','elevator_lobby','elevator_shaft','embassy','engine_room','entrance_hall','escalator-indoor',
 'excavation','fabric_store','farm','fastfood_restaurant','field-cultivated','field-wild','field_road','fire_escape','fire_station',
 'fishpond','flea_market-indoor','florist_shop-indoor','food_court','football_field','forest-broadleaf','forest_path',
 'forest_road','formal_garden','fountain','galley','garage-indoor','garage-outdoor','gas_station','gazebo-exterior',
 'general_store-indoor','general_store-outdoor','gift_shop','glacier','golf_course','greenhouse-indoor','greenhouse-outdoor',
 'grotto','gymnasium-indoor','hangar-indoor','hangar-outdoor','harbor','hardware_store','hayfield','heliport','highway','home_office',
 'home_theater','hospital','hospital_room','hot_spring','hotel-outdoor','hotel_room','house','hunting_lodge-outdoor',
 'ice_cream_parlor','ice_floe','ice_shelf','ice_skating_rink-indoor','ice_skating_rink-outdoor','iceberg','igloo','industrial_area',
 'inn-outdoor','islet','jacuzzi-indoor','jail_cell','japanese_garden','jewelry_shop','junkyard','kasbah','kennel-outdoor',
 'kindergarden_classroom','kitchen','lagoon','lake-natural','landfill','landing_deck','laundromat','lawn','lecture_room',
 'legislative_chamber','library-indoor','library-outdoor','lighthouse','living_room','loading_dock','lobby','lock_chamber',
 'locker_room','mansion','manufactured_home','market-indoor','market-outdoor','marsh','martial_arts_gym','mausoleum','medina',
 'mezzanine','moat-water','mosque-outdoor','motel','mountain','mountain_path','mountain_snowy','movie_theater-indoor','museum-indoor',
 'museum-outdoor','music_studio','natural_history_museum','nursery','nursing_home','oast_house','ocean','office','office_building',
 'office_cubicles','oilrig','operating_room','orchard','orchestra_pit','pagoda','palace','pantry','park','parking_garage-indoor',
 'parking_garage-outdoor','parking_lot','pasture','patio','pavilion','pet_shop','pharmacy','phone_booth','physics_laboratory',
 'picnic_area','pier','pizzeria','playground','playroom','plaza','pond','porch','promenade','pub-indoor','racecourse','raceway',
 'raft','railroad_track','rainforest','reception','recreation_room','repair_shop','residential_neighborhood','restaurant',
 'restaurant_kitchen','restaurant_patio','rice_paddy','river','rock_arch','roof_garden','rope_bridge','ruin','runway','sandbox',
 'sauna','schoolhouse','science_museum','server_room','shed','shoe_shop','shopfront','shopping_mall-indoor','shower','ski_resort',
 'ski_slope','sky','skyscraper','slum','snowfield','soccer_field','stable','stadium-baseball','stadium-football','stadium-soccer',
 'stage-indoor','stage-outdoor','staircase','storage_room','street','subway_station-platform','supermarket','sushi_bar','swamp',
 'swimming_hole','swimming_pool-indoor','swimming_pool-outdoor','synagogue-outdoor','television_room','television_studio',
 'temple-asia','throne_room','ticket_booth','topiary_garden','tower','toyshop','train_interior','train_station-platform','tree_farm',
 'tree_house','trench','tundra','underwater-ocean_deep','utility_room','valley','vegetable_garden','veterinarians_office','viaduct',
 'village','vineyard','volcano','volleyball_court-outdoor','waiting_room','water_park','water_tower','waterfall','watering_hole',
 'wave','wet_bar','wheat_field','wind_farm','windmill','yard','youth_hostel','zen_garden']

landmark_labels= ['Abu Simbel', 'Acropolis of Athens', 'Arc de Triomphe', 
'Atomium', 'Big Ben', 'Burj al Arab', 'CN Tower', 'Cathedral of Brasilia', 
'Chichen Itza', 'Christ the Redeemer', 'ChГteau de Chenonceau', 'Eiffel Tower',
'Fushimi Inari Taisha', 'Golden Gate Bridge', 'Great Buddha of Kamakura', 
'Guggenheim Museum', 'Hallgrimskirkja', 'Hawa Mahal', 'London Eye', 
'Lotus Temple', 'Louvre', 'Marina Bay Sands', 'Petra', 'Qutub Minar', 
'Red Square', 'Shwedagon Pagoda', 'Statue of Liberty', 'Stone Chariot', 
'Stonehenge', 'Sydney Harbour Bridge', 'Taj Mahal', 'The Colosseum', 
'The Gateway Arch', 'The Gherkin', 'Victoria Falls', 'brandenburg gate', 
'burj khalifa', 'cloud gate', 'golden temple', 'kaaba', 'le centre pompidou', 
'leaning tower of pisa', 'matrimandir', 'mt fuji', 'mt rushmore', 
'pyramids of giza', 'space needle', 'sultan ahmed mosque', 
'the great wall of china', 'washington monument']

sports_labels = ['air hockey', 'ampute football', 'archery', 'arm wrestling', 'axe throwing', 'balance beam', 'barell racing', 'baseball', 
'basketball', 'baton twirling', 'bike polo', 'billiards', 'bmx', 'bobsled', 'bowling', 'boxing', 'bull riding', 'bungee jumping', 
'canoe slamon', 'cheerleading', 'chuckwagon racing', 'cricket', 'croquet', 'curling', 'disc golf', 'fencing', 'field hockey', 
'figure skating men', 'figure skating pairs', 'figure skating women', 'fly fishing', 'football', 'formula 1 racing', 'frisbee', 
'gaga', 'giant slalom', 'golf', 'hammer throw', 'hang gliding', 'harness racing', 'high jump', 'hockey', 'horse jumping', 
'horse racing', 'horseshoe pitching', 'hurdles', 'hydroplane racing', 'ice climbing', 'ice yachting', 'jai alai', 'javelin', 
'jousting', 'judo', 'lacrosse', 'log rolling', 'luge', 'motorcycle racing', 'mushing', 'nascar racing', 'olympic wrestling', 
'parallel bar', 'pole climbing', 'pole dancing', 'pole vault', 'polo', 'pommel horse', 'rings', 'rock climbing', 'roller derby', 
'rollerblade racing', 'rowing', 'rugby', 'sailboat racing', 'shot put', 'shuffleboard', 'sidecar racing', 'ski jumping', 
'sky surfing', 'skydiving', 'snow boarding', 'snowmobile racing', 'speed skating', 'steer wrestling', 'sumo wrestling', 'surfing', 
'swimming', 'table tennis', 'tennis', 'track bicycle', 'trapeze', 'tug of war', 'ultimate', 'uneven bars', 'volleyball', 
'water cycling', 'water polo', 'weightlifting', 'wheelchair basketball', 'wheelchair racing', 'wingsuit flying']